#' Create a Phasing Dictionary for Transcripts and Domains
#'
#' This function generates a data frame summarizing gene, DoCo and transcript relationships in the annotation tracks.
#'
#' @param df A data frame containing transcript-domain mapping, with the following required columns:
#'   - \code{Transcript}: Transcript identifier.
#'   - \code{DoCo}: Domain-combination string (generated by `blessy.domainPhasing`).
#'   - \code{Gene}: Gene identifier.
#' @param bed_df The initial transcript annotation data frame with the following required columns:
#'   - \code{name}: Transcript identifier.
#'   - \code{geneName}: Gene identifier.
#'
#' @return A phasing dictionary data frame with the following columns:
#'   - \code{Transcript}: Transcript identifier.
#'   - \code{DoCo}: Domain-combination string.
#'   - \code{Gene}: Gene identifier.
#'
#' @importFrom dplyr select mutate distinct anti_join bind_rows
#'
#' @examples
#' # Example transcript-domain data frame
#' phased_df <- data.frame(
#'   Transcript = c("tx1", "tx2"),
#'   DoCo = c("domainA::chr1:1000-1100(+);;; geneA", ";;; geneB"),
#'   Gene = c("geneA", "geneB")
#' )
#'
#' # Example BED-like data frame
#' tx_df <- data.frame(
#'   name = c("tx1", "tx2", "tx3"),
#'   geneName = c("geneA", "geneB", "geneC")
#' )
#'
#' # Create the phasing dictionary
#' phasing_dict <- blessy.createPhasingDictionary(phased_df, tx_df)
#'
#' @export
blessy.createPhasingDictionary <- function(df, bed_df) {
  # Ensure required columns exist in df
  required_columns_df <- c("Transcript", "DoCo", "Gene")
  missing_columns_df <- setdiff(required_columns_df, colnames(df))
  if (length(missing_columns_df) > 0) {
    stop("The dataframe 'df' must contain the following columns: ", paste(missing_columns_df, collapse = ", "))
  }
  
  # Ensure required columns exist in bed_df
  required_columns_bed <- c("name", "geneName")
  missing_columns_bed <- setdiff(required_columns_bed, colnames(bed_df))
  if (length(missing_columns_bed) > 0) {
    stop("The BED dataframe 'bed_df' must contain the following columns: ", paste(missing_columns_bed, collapse = ", "))
  }
  
  # Subset df to required columns and remove duplicates
  phasing_dict <- df %>%
    select(Transcript, DoCo, Gene) %>%
    distinct()
  
  # Prepare the BED dataframe
  bed_transcripts <- bed_df %>%
    select(Transcript = name, Gene = geneName) %>%
    distinct()
  
  # Identify transcripts in bed_df not in phasing_dict
  missing_transcripts <- anti_join(bed_transcripts, phasing_dict, by = "Transcript")
  
  # For these transcripts, set DoCo to ";;;" followed by Gene
  missing_transcripts <- missing_transcripts %>%
    mutate(DoCo = paste0(";;; ", Gene))
  
  # Combine the missing transcripts with the phasing_dict
  phasing_dict <- bind_rows(phasing_dict, missing_transcripts)
  
  # Return the updated phasing dictionary
  return(phasing_dict)
}
